# Workflow meant to be used by external repositories
# that are configured with this `meta` repository
name: Gettext check

jobs:
  test:
    name: Dependencies report
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Install gettext
        run: |
          sudo apt install -y gettext
      - name: Check that *.mo files are created correctly
        run: |
          for po in `find . -name "*.po"` ; do msgfmt --no-hash -o `dirname $po`/`basename $po .po`.mo $po; done
